<a href="https://colab.research.google.com/github/vinodkumarreddy/Pytorch-learning/blob/main/autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
a = torch.rand(size = (1,10), requires_grad = True)

In [6]:
b = torch.rand(size = (1,1), requires_grad = True)

In [7]:
c = a + b

In [8]:
d = 2*a + b

In [9]:
e = c + d

In [10]:
e

tensor([[3.9611, 1.1966, 1.5678, 3.2795, 2.3820, 1.1358, 2.3833, 2.3381, 3.8542,
         1.1500]], grad_fn=<AddBackward0>)

In [11]:
e.grad_fn

In [13]:
e.grad_fn.next_functions

((<AddBackward0 at 0x7c9661d90040>, 0), (<AddBackward0 at 0x7c9661d92b90>, 0))

Each tensor generally has pointers to all the computations leading towards it. Here e is sum of c and d. So, its next functions have pointers towards gradients of c and d. Each of c and d have pointers to a and b as they are used in their calculation.

In [15]:
e.grad_fn.next_functions[0][0].next_functions

((<AccumulateGrad at 0x7c9661e3e6b0>, 0),
 (<AccumulateGrad at 0x7c9661e3f1f0>, 0))

In [17]:
e.grad_fn.next_functions[1][0].next_functions

((<MulBackward0 at 0x7c9661e3f460>, 0),
 (<AccumulateGrad at 0x7c9661e3f1f0>, 0))

In [18]:
e.grad_fn.next_functions[1][0].next_functions[0][0].next_functions

((<AccumulateGrad at 0x7c9661e3e6b0>, 0), (None, 0))

In [19]:
c.grad_fn.next_functions

((<AccumulateGrad at 0x7c9661e3e6b0>, 0),
 (<AccumulateGrad at 0x7c9661e3f1f0>, 0))

In [24]:
a = torch.rand(size = (1,2), requires_grad = True)

In [25]:
b = a[0][0] + 1

In [26]:
c = a[0][1] + 1

In [27]:
d = torch.prod(a)

In [30]:
d.grad_fn.next_functions

((<AccumulateGrad at 0x7c9661d92830>, 0),)

In [31]:
e = b * c

In [32]:
e.grad_fn

In [33]:
e.grad_fn.next_functions

((<AddBackward0 at 0x7c9661cf6140>, 0), (<AddBackward0 at 0x7c9661cf70d0>, 0))

In [35]:
e.grad_fn.next_functions[0][0].next_functions

((<SelectBackward0 at 0x7c9661e3fa60>, 0), (None, 0))

In [55]:
a = torch.ones((1,), requires_grad=False) * 2
a.requires_grad = True
print(a)

b1 = 2 * a**2
print(b1)

a.requires_grad = False
b2 = 2 * a
print(b2)

tensor([2.], requires_grad=True)
tensor([8.], grad_fn=<MulBackward0>)
tensor([4.])


In [56]:
a.grad

In [57]:
a.requires_grad = True

In [58]:
a.grad

In [59]:
b1.backward()

In [60]:
a.grad

tensor([8.])

In [61]:
dir(a)

['H',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed_

In [62]:
import torch.nn as nn

In [68]:
network = nn.Sequential(
    nn.Linear(20, 64),
    nn.ReLU(),
    nn.Linear(64, 3),
    nn.Sigmoid()
)

In [71]:
dir(network)

['T_destination',
 '__add__',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_backward_pre_hooks',
 '_buffers',
 '_call_impl',
 '_compiled_call_impl',
 '_forward_hooks',
 '_forward_hooks_always_called',
 '_forward_hooks_with_kwargs',
 '_forward_pre_hooks',
 '_forward_pre_hooks_with_kwargs',
 '_get_backward_hooks',
 '_get_backward_pre_hooks',
 '_get_item_by_idx',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_lo

In [73]:
network.requires_grad_?