<a href="https://colab.research.google.com/github/vinodkumarreddy/Pytorch-learning/blob/main/Pytorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First Section is on how to create a tensor. We already know all the corresponding functions. Then he discusses on random seeds and how initializing them would mean that the sequence of number generated given a random seed is deterministic. Then he moves on to shapes and like functions

In [ ]:
import torch
import torchvision

In [ ]:
a_t = torch.rand(size = (3,2))

In [ ]:
b_t = torch.ones_like(a_t)

In [ ]:
a_t.shape, b_t.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

Moves on to discuss how to convert standard python datatypes like list of lists etc into tensors using the torch.tensor function

Next is on datatypes and type conversions. By default most tensors are of the type float32. We can change the tensor format by specifying the requisite format while creating the tensor or we can also type cast the tensor using the .to function.

In [ ]:
a = torch.ones((3,2))

In [ ]:
a.dtype

torch.float32

In [ ]:
a.to(torch.int32).dtype

torch.int32

In [ ]:
a = [[1,1], [2,1]]

In [ ]:
a

[[1, 1], [2, 1]]

In [ ]:
a_t = torch.tensor(a)

In [ ]:
a_t.dtype

torch.int64

One of the cases where the default data type if inferred from the data is when we are converting some existing python datatype to tensor. It seems like the data type is being inferref from the data.

In [ ]:
a = [[1,1.1], [2.1,1.2]]

In [ ]:
torch.tensor(a).dtype

torch.float32

Generic math operations on tensors

In [ ]:
ones = torch.ones((3,4))
twos = ones*2
threes = twos + ones
fours = twos**2
sqrts = twos**0.5

In [ ]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
twos

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [ ]:
threes

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [ ]:
fours

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [ ]:
sqrts

tensor([[1.4142, 1.4142, 1.4142, 1.4142],
        [1.4142, 1.4142, 1.4142, 1.4142],
        [1.4142, 1.4142, 1.4142, 1.4142]])

Generally any operation with a scalar is broadcasted to the whole tensor. Similarly element wise operations occur when we are doing these operations between to tensors. There is also broadcasting in these cases as well

In [ ]:
# Double broadcasting test
a = torch.ones(size = (3,1))
b = torch.rand((1,2))
a, b

(tensor([[1.],
         [1.],
         [1.]]),
 tensor([[0.0298, 0.9041]]))

In [ ]:
a*b

tensor([[0.0298, 0.9041],
        [0.0298, 0.9041],
        [0.0298, 0.9041]])

There are also many math operations supported by pytorch. Need to check if every operation allows for gradient calculations

In [1]:
import torch

Testing out various functions available in pytorch

In [2]:
a_t = torch.rand(size = (2,2)) * 10 - 5

In [5]:
a_t

tensor([[-1.3697,  4.4144],
        [-4.0055, -2.3486]])

In [3]:
torch.abs(a_t)

tensor([[1.3697, 4.4144],
        [4.0055, 2.3486]])

In [6]:
torch.ceil(a_t)

tensor([[-1.,  5.],
        [-4., -2.]])

In [7]:
torch.floor(a_t)

tensor([[-2.,  4.],
        [-5., -3.]])

In [8]:
torch.clamp(a_t, -2, 2)

tensor([[-1.3697,  2.0000],
        [-2.0000, -2.0000]])

In [9]:
import math

In [10]:
math.pi

3.141592653589793

In [11]:
angle_t = torch.tensor([math.pi/4, math.pi/3, math.pi/2, math.pi])

In [12]:
torch.sin(angle_t)

tensor([ 7.0711e-01,  8.6603e-01,  1.0000e+00, -8.7423e-08])

In [14]:
torch.cos(angle_t)

tensor([ 7.0711e-01,  5.0000e-01, -4.3711e-08, -1.0000e+00])

In [15]:
torch.asin(torch.sin(angle_t))

tensor([ 7.8540e-01,  1.0472e+00,  1.5708e+00, -8.7423e-08])

In [16]:
angle_t

tensor([0.7854, 1.0472, 1.5708, 3.1416])

In [17]:
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e))

tensor([[ True, False],
        [False, False]])


In [18]:
d == e

tensor([[ True, False],
        [False, False]])

In [19]:
d >= e

tensor([[True, True],
        [True, True]])

In [20]:
torch.max??

In [21]:
a_t = torch.rand(size = (2,3,2))

In [22]:
a_t

tensor([[[0.0660, 0.9148],
         [0.6369, 0.0686],
         [0.9092, 0.6599]],

        [[0.0113, 0.7694],
         [0.4297, 0.9270],
         [0.5566, 0.8728]]])

In [24]:
torch.max(a_t)

tensor(0.9270)

In [25]:
torch.max(input = a_t, dim = 0)

torch.return_types.max(
values=tensor([[0.0660, 0.9148],
        [0.6369, 0.9270],
        [0.9092, 0.8728]]),
indices=tensor([[0, 0],
        [0, 1],
        [0, 1]]))

In [26]:
torch.max(input = a_t, dim = 1)

torch.return_types.max(
values=tensor([[0.9092, 0.9148],
        [0.5566, 0.9270]]),
indices=tensor([[2, 0],
        [2, 1]]))

In case of converting the predicted values to corresponding class

In [27]:
outputs = torch.rand(size = (100, 20))

In [29]:
output_class_probs, output_classes = torch.max(outputs, dim = 1)

In [31]:
output_classes.shape

torch.Size([100])

In [32]:
torch.mean(a_t, dim = 0).shape

torch.Size([3, 2])

In [33]:
torch.mean??

In [34]:
torch.std(a_t)

tensor(0.3494)

In [35]:
torch.prod(a_t)

tensor(2.6755e-06)

Assigning a tensor to another would not copy the tensor. Instead it just copies the pointer. We would need to explicitly use the clone method to copy a tensor. Clone also looks at the original autograd settings of the tensor. If the original has grad turned on then clone will also have it and any gradient will be propogated to the original while doing backward(). There is also the detach method. While just gets the tensor values without affecting the computational gradient. Does it create a clone?

In [38]:
a = torch.rand(size = (3,4), requires_grad = True)

In [39]:
a

tensor([[0.3308, 0.2392, 0.7425, 0.6823],
        [0.3806, 0.0097, 0.3490, 0.1767],
        [0.9397, 0.1434, 0.4187, 0.0665]], requires_grad=True)

In [40]:
b = a.detach()

In [42]:
assert b is not a

In [44]:
id(a)

139525899083328

In [45]:
id(b)

139525901405856

In [47]:
b[0][1] = 1

In [48]:
a

tensor([[0.3308, 1.0000, 0.7425, 0.6823],
        [0.3806, 0.0097, 0.3490, 0.1767],
        [0.9397, 0.1434, 0.4187, 0.0665]], requires_grad=True)

It seems like detach doesn't copy the contents for the new tensor. It should be a better idea to first detach and then do a clone so that there is no linkage between the newly created tensor and the original tensor

In [49]:
"gpu" if torch.cuda.is_available() else "cpu"

'cpu'

Shape editing for tensors

In [51]:
a = torch.rand(size = (3, 32, 32))

In [52]:
a.shape

torch.Size([3, 32, 32])

In [54]:
a.unsqueeze(0).shape

torch.Size([1, 3, 32, 32])

In [55]:
a.unsqueeze(1).shape

torch.Size([3, 1, 32, 32])

In [56]:
a.unsqueeze(2).shape

torch.Size([3, 32, 1, 32])

In [57]:
a = torch.rand(size = (1, 20))

In [58]:
a.shape

torch.Size([1, 20])

In [59]:
a.squeeze().shape

torch.Size([20])