<a href="https://colab.research.google.com/github/vinodkumarreddy/Pytorch-learning/blob/main/Pytorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First Section is on how to create a tensor. We already know all the corresponding functions. Then he discusses on random seeds and how initializing them would mean that the sequence of number generated given a random seed is deterministic. Then he moves on to shapes and like functions

In [1]:
import torch
import torchvision

In [2]:
a_t = torch.rand(size = (3,2))

In [3]:
b_t = torch.ones_like(a_t)

In [4]:
a_t.shape, b_t.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

Moves on to discuss how to convert standard python datatypes like list of lists etc into tensors using the torch.tensor function

Next is on datatypes and type conversions. By default most tensors are of the type float32. We can change the tensor format by specifying the requisite format while creating the tensor or we can also type cast the tensor using the .to function.

In [5]:
a = torch.ones((3,2))

In [6]:
a.dtype

torch.float32

In [8]:
a.to(torch.int32).dtype

torch.int32

In [9]:
a = [[1,1], [2,1]]

In [10]:
a

[[1, 1], [2, 1]]

In [11]:
a_t = torch.tensor(a)

In [12]:
a_t.dtype

torch.int64

One of the cases where the default data type if inferred from the data is when we are converting some existing python datatype to tensor. It seems like the data type is being inferref from the data.

In [13]:
a = [[1,1.1], [2.1,1.2]]

In [14]:
torch.tensor(a).dtype

torch.float32

Generic math operations on tensors

In [19]:
ones = torch.ones((3,4))
twos = ones*2
threes = twos + ones
fours = twos**2
sqrts = twos**0.5

In [20]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
twos

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [22]:
threes

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [23]:
fours

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [24]:
sqrts

tensor([[1.4142, 1.4142, 1.4142, 1.4142],
        [1.4142, 1.4142, 1.4142, 1.4142],
        [1.4142, 1.4142, 1.4142, 1.4142]])

Generally any operation with a scalar is broadcasted to the whole tensor. Similarly element wise operations occur when we are doing these operations between to tensors. There is also broadcasting in these cases as well

In [25]:
# Double broadcasting test
a = torch.ones(size = (3,1))
b = torch.rand((1,2))
a, b

(tensor([[1.],
         [1.],
         [1.]]),
 tensor([[0.0298, 0.9041]]))

In [26]:
a*b

tensor([[0.0298, 0.9041],
        [0.0298, 0.9041],
        [0.0298, 0.9041]])

There are also many math operations supported by pytorch. Need to check if every operation allows for gradient calculations